import checkoutFormModel from "./checkoutFormModel";

const {
  formField: {
    salutation,
    firstName,
    lastName,
    email,
    password,
    fathername,
    cnic,
    image,
    Phonenumber,
    addressI,
    city,
    zipcode,
    country,
    useAddressForPaymentDetails,
    qualificationname,
    institute,
    // expiryDate,
    employer,
    position,
    qualificationCountry,
    departmentName,
    designationName,
    grade,
    workphone,
    reporting,
    Employeetype,
    role,
    sourceofhire,
    joiningDate,
    profileImage,
  },
} = checkoutFormModel;

const initialFormValues = {
  [salutation.name]: "",
  [firstName.name]: "",
  [lastName.name]: "",
  [email.name]: "",
  [password.name]: "",
  [fathername.name]: "",
  [cnic.name]: "",
  [Phonenumber.name]: "",
  [addressI.name]: "",
  // [image.name]: {
  //   file: null,
  //   src: null,
  //   name: ""
  // },
  [city.name]: "",
  [zipcode.name]: "",
  [country.name]: "",
  [useAddressForPaymentDetails.name]: false,
  [qualificationname.name]: "",
  [institute.name]: "",
  [employer.name]: "",
  [position.name]: "",
  [qualificationCountry.name]: "",
  [departmentName.name]: "",
  [designationName.name]: "",
  [grade.name]: "",
  [workphone.name]: "",
  [reporting.name]: "",
  [sourceofhire.name]: "",
  [Employeetype.name]: "",
  [role.name]: "",
  [joiningDate]: "",
  [profileImage.name]: "",
};

export default initialFormValues;
